#!/bin/bash
#
# issabel-firstboot    This shell script sets up the various MySQL databases for the
#                       modules that need an initialized database to work. Other tasks
#                       to be performed on first boot should be placed here.
#
# chkconfig: 2345 66 1
# description:    Issabel setup for first boot.

# Source function library.
# . /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Currently this is dead code
issabel_activate_firewall(){
    salida=1
    dialog --colors --title "\Z1 Attention" --backtitle "Issabel Firewall Settings" --ok-label "Continue" --msgbox "Default Firewall Rules will be activated on the system upon finishing the installation.\n\nIf you want to review or modify the applied rules, you can do so\nin the web GUI by navigating to:\n\nSecurity > Firewall" 12 70
    if [ -f "/usr/share/issabel/privileged/fwconfig" ]; then
        /usr/bin/issabel-helper fwconfig --load 2>&1
        tmp=$?
        if [ $tmp -eq 0 ]; then
            sqlite3 /var/www/db/iptables.db "update tmp_execute set first_time = 0 ,exec_in_sys = 1" > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                echo "Firewall actived successfully."
                salida=0
            fi
        else
            echo "Firewall can't be actived. Please activated your Firewall from from Issabel web interface: Security > Firewall > Firewall Rules."
        fi
    else
        echo "Firewall can't be actived. Don't exits file /usr/share/issabel/privileged/fwconfig"
    fi
    return $salida
}

check_manager_issabelPBX(){
    grep "^writetimeout" /etc/asterisk/manager.conf >/dev/null
    if [ $? -gt 0 ]; then
        echo "manager.conf file from samples, needs to be updated"
        # No writetimeout in manager.conf, it might be the stock asterisk one, we need to replace it with the issasbelPBX one
        issabel_ami_password=`grep amiadminpwd= /etc/issabel.conf | sed 's/^amiadminpwd=//'`
        issabel_mysql_password=`grep mysqlrootpwd= /etc/issabel.conf | sed 's/^mysqlrootpwd=//'`
        if [ -f /etc/asterisk.issabel/manager.conf ]; then
            echo "cp  /etc/asterisk.issabel/manager.conf /etc/asterisk"
            cp  /etc/asterisk.issabel/manager.conf /etc/asterisk
            ls -la /etc/asterisk/manager.conf
            sed -i "s/AMPMGRPASS/${issabel_ami_password}/" /etc/asterisk/manager.conf
            service asterisk restart
            /var/www/html/admin/modules/framework/install_amp --username=root --password=${issabel_mysql_password}
            service asterisk restart
        else
          echo "no asterisk.issabel manager.conf file present"
       fi
   else
       echo "manager.conf ok"
       cat /etc/asterisk/manager.conf
   fi
   sleep 10
}

start() {
    ret=0

    /sbin/amportal chown >/dev/null 2>&1

    /usr/bin/issabel-admin-passwords --init
    ret=$?

    check_manager_issabelPBX

    [ $ret -eq 0 -a -d /var/lock/subsys ] && touch /var/lock/subsys/issabel-firstboot

    return $ret
}

stop(){
    [ -f "/var/lock/subsys/issabel-firstboot" ] && rm -f /var/lock/subsys/issabel-firstboot
    return 0
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 1
esac

exit $?
