#!/bin/bash
function check_dialog()
{
    if ! dialog &> /dev/null
    then 
        echo "ERROR: dialog binary not found."
        exit 1
    fi
}
function check_database()
{
    if ! mysql -uroot -p$mysqlrootpwd asterisk -e "show tables" &> /dev/null
    then
        echo "ERROR: Cannot connect to Datbase."
        exit 1
    fi
}
function logo()
{
  dialog --stdout --sleep 1 --backtitle "$BACKTITLE" \
         --infobox " O @ @\n @ @ O\n @ O O\n   O\nIssabel" \
        7 11
}
check_dialog
source /etc/issabel.conf
if [ -z $mysqlrootpwd ]
then
    echo "ERROR: Cannot load /etc/issabel.conf"
    exit 1
fi
check_database

currentLang=$(sqlite3 /var/www/db/settings.db "select value from settings where key='language'")
langselected_en=on
langselected_es=off
langselected_br=off
langselected_fr=off
langselected_fa=off

if [ "x$currentLang" != "x" ];then 
langselected_en=off
declare langselected_${currentLang}=on
fi

selLang=$((dialog --backtitle "Issabel" --no-tags \
--radiolist "Select PBX language:" 15 40 10 \
 en "English" $langselected_en \
 es "Spanish" $langselected_es \
 pt_BR "Portuguese(BR)" $langselected_br \
 fr "French" $langselected_fr \
 pr "Persian" $langselected_fa \
 > /dev/tty) 2>&1)
if [ -z $selLang ]
then
    #No language selected
    exit 2
fi

#Set *non standard* GUI languages
case $selLang in
    pt_BR)
        webLang="br"
	fopLang="pt_BR"
    ;;
    pr)
        webLang="fa"
	fopLang="en"
    ;;
    fr)
	fopLang="fr_FR"
        webLang=$selLang
    ;;
    *)
        webLang=$selLang
	fopLang=$selLang
    ;;
esac

(
  sqlite3 /var/www/db/settings.db "update settings set value='$webLang' where key='language'"
  if [ -f /usr/local/fop2/fop2settings.db ]
  then
      sqlite3 /usr/local/fop2/fop2settings.db "update setup set value=\"'$fopLang'\" WHERE extension='SETTINGS' and context='GENERAL' and parameter='language'";
  fi
  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO sipsettings(keyword,data) VALUES('sip_language','$selLang');"
  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO iaxsettings(keyword,data) VALUES('iax_language','$selLang');"
  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO pjsipsettings(keyword,data) VALUES('sip_language','$selLang');"
  #DAHDI
  DAHDI_CFG="/etc/asterisk/chan_dahdi.conf"
  if grep -q "language=" $DAHDI_CFG
  then
      sed -i "s/^language=.*/language=$selLang/g" $DAHDI_CFG
  else
      sed -i "/^\[channels\]/a language=$selLang" $DAHDI_CFG
  fi
  sed -i "s/.*defaultlanguage.*/defaultlanguage=$selLang/" /etc/asterisk/asterisk.conf
) &> /dev/null
logo
if ! amportal a r &> /dev/null
then
    clear
    echo "ERROR: Cannot apply changes."
    exit 3
else
    clear
fi

